#!/usr/bin/env bash
# check_phase_2.sh — Gate check for Phase 2 — Policy Engine
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 2 — Policy Engine ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/1] Policy engine validates a project config... "
if python src/policy_engine.py --check project.yaml > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Policy engine validates a project config")
    ERRORS+=("        Command: python src/policy_engine.py --check project.yaml")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 2 — Policy Engine — ALL CHECKS PASSED"
