#!/usr/bin/env bash
# check_phase_4.sh — Gate check for Phase 4 — Publication Artifacts
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 4 — Publication Artifacts ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/1] Blog draft exists... "
if test -f blog/draft.md > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Blog draft exists")
    ERRORS+=("        Command: test -f blog/draft.md")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 4 — Publication Artifacts — ALL CHECKS PASSED"
