#!/usr/bin/env bash
# sweep.sh — Orchestrate all experiments for govML Agent-Native Governance Platform
# AUTO-GENERATED by gen_sweep.py from project.yaml
# Re-run generator after changing project.yaml experiment matrix.
set -euo pipefail

SEEDS="42"
PARTS="all"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    echo "Usage: bash $0 [--parts {1,2,all}] [--seeds SEED_LIST]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --parts) PARTS="$2"; shift 2 ;;
        --seeds) SEEDS="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; usage ;;
    esac
done

IFS=',' read -ra SEED_ARRAY <<< "$SEEDS"
cd "$PROJECT_DIR"
export PYTHONHASHSEED=0

run_part1() {
    echo "=== Part 1: mcp_server ==="
    for method in policy_reader gate_checker template_filler; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/test_mcp_server.py \
                --method $method --seed $seed
        done
    done
}

run_part2() {
    echo "=== Part 2: policy_engine ==="
    for method in yaml_policies gate_enforcement; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/test_policies.py \
                --method $method --seed $seed
        done
    done
}

case "$PARTS" in
    1) run_part1 ;;
    2) run_part2 ;;
    all) run_part1; run_part2 ;;
    *) echo "Unknown part: $PARTS"; usage ;;
esac

echo ''
echo "=== Sweep complete ==="
